theme: jekyll-theme-minimal
collections:
  2015-03:
    permalink: /:title/:path
    title: Old newsletter
    date: 2015-11-04
  2018-00:
    permalink: /:title/:path
    title: Zero emission
    date: 2018-01-01
  2018-01:
    permalink: /:title/:path
    title: First release!
    date: 2018-03-01