theme: jekyll-theme-tactile
google_analytics: UA-114571919-1
collections:
  2015-03:
    permalink: /:collection/:path
    title: Old newsletter
    date: 2015-11-04
    output: true
  2018-01:
    permalink: /:collection/:path
    title: First release!
    date: 2018-03-01
    output: true
  2018-00:
    permalink: /:collection/:path
    title: Zero emission
    date: 2018-01-01
    output: true
